const stages=['Intake','Specialty Routing','Engagement','Payment Clearance','Authorized for Prep','Preparation','Taxpayer Data Entry','DE-017','Quality Review','QR PASS','Signature','Final Payment / Release','Transmission','Acceptance','Delivery','Commission','Archive'];
const cases=[
{name:'Sample Taxpayer A',year:2025,type:'1040 + Schedule C',status:'Ready for Quality Review',stage:8,owner:'A. Preparer',reviewer:'J. Reviewer',next:'Complete CT-005 — Quality Review Packet.',controls:['PGI-001 / CT-001 — Elite Client Interview complete','PGI-002 — Business Interview complete','EC-002 — Engagement & Fee Authorization complete','RC-001 — Payment & Revenue Control cleared','DE-017 — Final Data Entry Verification complete'],audit:['DE-017 completed by A. Preparer','Taxpayer Data Entry marked complete','Business workpapers reconciled']},
{name:'Sample Taxpayer B',year:2025,type:'1040',status:'Waiting on Taxpayer',stage:1,owner:'A. Preparer',reviewer:'Unassigned',next:'Collect missing W-2 before preparation can continue.',controls:['PGI-001 / CT-001 — Elite Client Interview complete','Missing source document: W-2'],audit:['Missing document request sent','Intake received']},
{name:'Sample Taxpayer C',year:2025,type:'1040 + Rental',status:'Payment Arrangement Pending',stage:3,owner:'M. Preparer',reviewer:'J. Reviewer',next:'Clear required payment arrangement in RC-001 — Payment & Revenue Control Sheet.',controls:['PGI-004 — Rental Property Interview complete','EC-002 — Engagement & Fee Authorization complete','RC-001 — Payment clearance pending'],audit:['Engagement accepted','Scope issued','Rental routing completed']},
{name:'Sample Taxpayer D',year:2025,type:'1040',status:'Ready to Transmit',stage:12,owner:'M. Preparer',reviewer:'J. Reviewer',next:'ERO/transmitter release and transmission.',controls:['CT-005 — Quality Review Packet: QR PASS','Taxpayer signature complete','Final RC-001 release clearance complete'],audit:['Final release clearance completed','Taxpayer signed authorization','QR PASS approved']}
];
let active=0;
function cls(s){if(s.includes('Ready'))return 'blue';if(s.includes('Waiting')||s.includes('Pending'))return 'amber';if(s.includes('PASS')||s.includes('Accepted'))return 'green';return 'red'}
function renderRows(){document.getElementById('queue').innerHTML=cases.map((c,i)=>`<tr onclick="openCase(${i})"><td><b>${c.name}</b></td><td>${c.type}</td><td><span class="status ${cls(c.status)}">${c.status}</span></td><td>${c.next}</td></tr>`).join('');document.getElementById('clientRows').innerHTML=cases.map((c,i)=>`<tr onclick="openCase(${i})"><td><b>${c.name}</b></td><td>${c.year}</td><td>${c.type}</td><td>${c.owner}</td><td><span class="status ${cls(c.status)}">${c.status}</span></td></tr>`).join('')}
function view(id,btn){['dashboard','clients','case'].forEach(x=>document.getElementById(x).classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(btn){document.querySelectorAll('.side button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}}
function openCase(i){active=i;const c=cases[i];view('case');document.getElementById('caseName').textContent=c.name;document.getElementById('caseMeta').textContent=`Tax Year ${c.year} · ${c.type}`;document.getElementById('caseStatus').textContent=c.status;document.getElementById('stages').innerHTML=stages.map((s,n)=>`<span class="stage ${n<c.stage?'done':n===c.stage?'current':''}">${s}</span>`).join('');document.getElementById('caseDetails').innerHTML=`<div class='row'><b>Assigned Preparer</b><span>${c.owner}</span></div><div class='row'><b>Assigned Reviewer</b><span>${c.reviewer}</span></div><div class='row'><b>Current Stage</b><span>${stages[c.stage]}</span></div><div class='row'><b>Tax Year</b><span>${c.year}</span></div><div class='row'><b>Return Profile</b><span>${c.type}</span></div>`;document.getElementById('controls').innerHTML=c.controls.map((x,n)=>`<label class='check'><input type='checkbox' ${n<c.controls.length-1?'checked':''}><span>${x}</span></label>`).join('');document.getElementById('nextAction').innerHTML=`<b>${c.next}</b>`;document.getElementById('audit').innerHTML=c.audit.map(x=>`<div>${x}</div>`).join('')}
function advanceCase(){const c=cases[active];if(c.stage<stages.length-1){c.audit.unshift(`${stages[c.stage]} control completed in prototype`);c.stage++;c.status=stages[c.stage];c.next=`Continue to ${stages[Math.min(c.stage+1,stages.length-1)]}.`;openCase(active);renderRows()}}
renderRows();
